// src/modules/parceiros/components/ParceirosSection.vue
<template>
  <aside
    id="parceiros-sidebar"
    aria-labelledby="parceiros-sidebar-title"
    class="parceiros-sidebar py-6 px-4 transition-colors duration-300 h-full flex flex-col"
  >
    <header class="mb-6 text-center">
      <h2
        id="parceiros-sidebar-title"
        class="text-lg md:text-xl font-bold"
      >
        Nossos Colaboradores
      </h2>
      <p class="text-xs text-gray-600 dark:text-gray-400 mt-1">
        Parceiros Comerciais da AMAJAC
      </p>
    </header>
    <!-- Loading -->
    <div v-if="loading" class="flex-1 flex flex-col items-center justify-center py-8">
      <div class="inline-block h-6 w-6 animate-spin rounded-full border-2 border-amajac-green border-t-transparent"></div>
      <p class="mt-3 text-sm">Carregando...</p>
    </div>
    <!-- Erro -->
    <div v-else-if="error" class="flex-1 flex flex-col items-center justify-center py-8 text-center">
      <p class="text-sm mb-2">{{ error }}</p>
      <button
        @click="fetchParceiros"
        class="text-xs px-3 py-1.5 rounded bg-amajac-green text-white hover:bg-amajac-green-hover focus:outline-none"
        aria-label="Tentar carregar novamente os parceiros comerciais"
      >
        Tentar novamente
      </button>
    </div>
    <!-- Lista -->
    <div
      v-else-if="parceiros.length > 0"
      role="list"
      class="space-y-4 overflow-y-auto flex-1"
    >
      <article
        v-for="p in parceiros"
        :key="p.id"
        role="listitem"
        class="bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md transition-shadow p-4"
      >
        <div class="flex items-start gap-3">
          <div class="flex-shrink-0 w-12 h-12 flex items-center justify-center">
            <img
              v-if="p.logo_url"
              :src="p.logo_url"
              :alt="p.imagem_alt"
              class="w-full h-full object-contain"
              loading="lazy"
              @error="p.logo_url = null"
            />
            <div v-else class="text-lg font-bold text-amajac-green">
              {{ p.nome.charAt(0).toUpperCase() }}
            </div>
          </div>
          <div class="min-w-0 flex-1">
            <h3 class="text-sm font-semibold text-gray-800 dark:text-white truncate">
              {{ p.nome }}
            </h3>
            <p v-if="p.ramo" class="text-xs text-gray-600 dark:text-gray-400 truncate">
              {{ p.ramo }}
            </p>
            <div class="mt-2 flex flex-wrap gap-1">
              <a
                v-if="p.link_site"
                :href="p.link_site"
                target="_blank"
                rel="noopener noreferrer"
                class="text-[10px] text-amajac-green hover:underline"
                :aria-label="`Site de ${p.nome}`"
              >
                Site
              </a>
              <!-- ✅ CORREÇÃO: removido espaço após domínio -->
              <a
                v-if="p.instagram"
                :href="`https://instagram.com/${p.instagram}`"
                target="_blank"
                rel="noopener noreferrer"
                class="text-[10px] text-pink-600 hover:underline dark:text-pink-400"
                :aria-label="`Instagram de ${p.nome}`"
              >
                IG
              </a>
              <!-- ✅ CORREÇÃO: removido espaço após domínio -->
              <a
                v-if="p.facebook"
                :href="`https://facebook.com/${p.facebook}`"
                target="_blank"
                rel="noopener noreferrer"
                class="text-[10px] text-blue-600 hover:underline dark:text-blue-400"
                :aria-label="`Facebook de ${p.nome}`"
              >
                FB
              </a>
            </div>
          </div>
        </div>
      </article>
    </div>
    <!-- Vazio -->
    <div v-else class="flex-1 flex items-center justify-center py-8 text-center">
      <p class="text-sm text-gray-500 dark:text-gray-400">Nenhum parceiro ativo.</p>
    </div>
  </aside>
</template>
<script setup>
import { onMounted } from 'vue'
import { useParceiros } from '../composables/useParceiros'
const { parceiros, loading, error, fetchParceiros } = useParceiros()
onMounted(() => {
  fetchParceiros()
})
</script>
<style scoped>
.parceiros-sidebar {
  --amajac-green: #2E7D32;
  --amajac-green-hover: #256a2a;
  background-color: #f9fafb;
  color: #4b5563;
  height: 100%;
  display: flex;
  flex-direction: column;
}
.parceiros-sidebar h2,
.parceiros-sidebar h3 {
  color: #1f2937;
}
.dark .parceiros-sidebar {
  background-color: #111827;
  color: #d1d5db;
}
.dark .parceiros-sidebar h2,
.dark .parceiros-sidebar h3 {
  color: #f9fafb;
}
.text-amajac-green { color: var(--amajac-green); }
.bg-amajac-green { background-color: var(--amajac-green); }
.bg-amajac-green-hover:hover { background-color: var(--amajac-green-hover); }
</style>

// next-app/src/components/ParceirosSection.tsx
'use client';

import { useState, useEffect } from 'react';
import { supabase } from '@/core/utils/supabaseClient';

interface Parceiro {
  id: string;
  nome: string;
  logo_url: string | null;
  link_site: string | null;
  instagram: string | null;
  facebook: string | null;
  ramo: string | null;
  imagem_alt: string;
}

export default function ParceirosSection() {
  const [parceiros, setParceiros] = useState<Parceiro[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchParceiros = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: err } = await supabase
        .from('parceiros_comerciais')
        .select('id, nome, logo_url, link_site, instagram, facebook, ramo, imagem_alt')
        .eq('ativo', true)
        .order('nome', { ascending: true });

      if (err) throw err;

      const formatados = (data || []).map((p: any) => ({
        ...p,
        link_site: p.link_site?.trim() || null,
        instagram: p.instagram?.trim() || null,
        facebook: p.facebook?.trim() || null,
        imagem_alt: p.imagem_alt || p.nome || 'Logo do parceiro',
      }));

      setParceiros(formatados);
    } catch (e) {
      console.error('Erro ao buscar parceiros:', e);
      setError('Não foi possível carregar os parceiros.');
      setParceiros([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchParceiros();
  }, []);

  const handleImageError = (index: number) => {
    const novos = [...parceiros];
    novos[index].logo_url = null;
    setParceiros(novos);
  };

  return (
    <aside
      id="parceiros-sidebar"
      aria-labelledby="parceiros-sidebar-title"
      className="parceiros-sidebar bg-gray-50 dark:bg-gray-900 text-gray-600 dark:text-gray-300 py-6 px-4 transition-colors duration-300 h-full flex flex-col"
    >
      <header className="mb-6 text-center">
        <h2
          id="parceiros-sidebar-title"
          className="text-lg md:text-xl font-bold text-gray-900 dark:text-white"
        >
          Nossos Colaboradores
        </h2>
        <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">
          Parceiros Comerciais da AMAJAC
        </p>
      </header>

      {loading ? (
        <div className="flex-1 flex flex-col items-center justify-center py-8">
          <div className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-[#2E7D32] border-t-transparent"></div>
          <p className="mt-3 text-sm">Carregando...</p>
        </div>
      ) : error ? (
        <div className="flex-1 flex flex-col items-center justify-center py-8 text-center">
          <p className="text-sm mb-2">{error}</p>
          <button
            onClick={fetchParceiros}
            className="text-xs px-3 py-1.5 rounded bg-[#2E7D32] text-white hover:bg-[#256a2a] focus:outline-none"
            aria-label="Tentar carregar novamente os parceiros comerciais"
          >
            Tentar novamente
          </button>
        </div>
      ) : parceiros.length > 0 ? (
        <div role="list" className="space-y-4 overflow-y-auto flex-1 pb-8">
          {parceiros.map((p, idx) => (
            <article
              key={p.id}
              role="listitem"
              className="bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md transition-shadow p-4"
            >
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-12 h-12 flex items-center justify-center">
                  {p.logo_url ? (
                    <img
                      src={p.logo_url}
                      alt={p.imagem_alt}
                      className="w-full h-full object-contain"
                      loading="lazy"
                      onError={() => handleImageError(idx)}
                    />
                  ) : (
                    <div className="text-lg font-bold text-[#2E7D32]">
                      {p.nome.charAt(0).toUpperCase()}
                    </div>
                  )}
                </div>
                <div className="min-w-0 flex-1">
                  <h3 className="text-sm font-semibold text-gray-800 dark:text-white truncate">
                    {p.nome}
                  </h3>
                  {p.ramo && (
                    <p className="text-xs text-gray-600 dark:text-gray-400 truncate">
                      {p.ramo}
                    </p>
                  )}
                  <div className="mt-2 flex flex-wrap gap-1">
                    {p.link_site && (
                      <a
                        href={p.link_site}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[10px] text-[#2E7D32] hover:underline"
                        aria-label={`Site de ${p.nome}`}
                      >
                        Site
                      </a>
                    )}
                    {p.instagram && (
                      <a
                        href={`https://instagram.com/${p.instagram}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[10px] text-pink-600 hover:underline dark:text-pink-400 ml-1"
                        aria-label={`Instagram de ${p.nome}`}
                      >
                        IG
                      </a>
                    )}
                    {p.facebook && (
                      <a
                        href={`https://facebook.com/${p.facebook}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[10px] text-blue-600 hover:underline dark:text-blue-400 ml-1"
                        aria-label={`Facebook de ${p.nome}`}
                      >
                        FB
                      </a>
                    )}
                  </div>
                </div>
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center py-8 text-center">
          <p className="text-sm text-gray-500 dark:text-gray-400">Nenhum parceiro ativo.</p>
        </div>
      )}
    </aside>
  );
}
