// next-app/src/components/ui/ModalContato.tsx
'use client';

import { useState, useEffect } from 'react';
import { supabase } from '@/core/utils/supabaseClient';

export default function ModalContato() {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    nome: '',
    email: '',
    telefone: '',
    assunto: '',
    mensagem: '',
  });

  useEffect(() => {
    const handleOpen = () => setIsOpen(true);
    window.addEventListener('openContactModal', handleOpen);
    return () => window.removeEventListener('openContactModal', handleOpen);
  }, []);

  const close = () => {
    setFormData({ nome: '', email: '', telefone: '', assunto: '', mensagem: '' });
    setIsOpen(false);
  };

  const closeOnOverlay = (e: React.MouseEvent<HTMLDivElement>) => {
    if ((e.target as HTMLElement).classList.contains('modal-overlay')) {
      close();
    }
  };

  const enviarMensagem = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { nome, email, telefone, assunto, mensagem } = formData;
      if (!nome || !email || !assunto || !mensagem) {
        alert('Por favor, preencha todos os campos obrigatórios.');
        setLoading(false);
        return;
      }

      const dadosParaEnviar = {
        nome: nome.trim(),
        email: email.trim().toLowerCase(),
        telefone: telefone?.trim() || null,
        assunto: assunto.trim(),
        mensagem: mensagem.trim(),
        lida: false,
        created_at: new Date().toISOString(),
      };

      const { error: supabaseError } = await supabase
        .from('mensagens_contato')
        .insert([dadosParaEnviar])
        .select('id')
        .single();

      if (supabaseError) throw supabaseError;

      alert('Mensagem enviada com sucesso! Entraremos em contato em breve.');
      close();
    } catch (err: any) {
      console.error('Erro ao enviar mensagem:', err);
      alert('Erro ao enviar mensagem. Tente novamente.');
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div 
      className="modal-overlay fixed inset-0 bg-black/50 flex items-center justify-center z-[9999] p-4" 
      onClick={closeOnOverlay}
    >
      <div 
        className="modal-content bg-white dark:bg-gray-800 dark:text-white rounded-xl w-full max-w-[500px] max-h-[90vh] overflow-y-auto shadow-2xl" 
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header flex justify-between items-center p-6 border-b border-gray-200 dark:border-gray-700">
          <h2 className="modal-title text-xl font-bold text-gray-800 dark:text-white m-0">Fale Conosco</h2>
          <button onClick={close} className="modal-close-btn bg-transparent border-none text-gray-500 hover:text-gray-700 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700 p-1.5 rounded transition-all cursor-pointer">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <form onSubmit={enviarMensagem} className="modal-form p-6 space-y-4">
          <div className="form-group">
            <label htmlFor="nome" className="block font-semibold mb-2 text-gray-700 dark:text-gray-300">Nome *</label>
            <input
              id="nome"
              value={formData.nome}
              onChange={(e) => setFormData({...formData, nome: e.target.value})}
              type="text"
              required
              className="w-full p-3 border border-gray-300 dark:border-gray-600 rounded-md text-sm transition-all dark:bg-gray-700 dark:text-white focus:outline-none focus:border-[#2E7D32] dark:focus:border-[#4CAF50] focus:ring-[3px] focus:ring-[#2E7D32]/10 dark:focus:ring-[#4CAF50]/10"
              placeholder="Seu nome completo"
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email" className="block font-semibold mb-2 text-gray-700 dark:text-gray-300">E-mail *</label>
            <input
              id="email"
              value={formData.email}
              onChange={(e) => setFormData({...formData, email: e.target.value})}
              type="email"
              required
              className="w-full p-3 border border-gray-300 dark:border-gray-600 rounded-md text-sm transition-all dark:bg-gray-700 dark:text-white focus:outline-none focus:border-[#2E7D32] dark:focus:border-[#4CAF50] focus:ring-[3px] focus:ring-[#2E7D32]/10 dark:focus:ring-[#4CAF50]/10"
              placeholder="seu@email.com"
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="telefone" className="block font-semibold mb-2 text-gray-700 dark:text-gray-300">Telefone (opcional)</label>
            <input
              id="telefone"
              value={formData.telefone}
              onChange={(e) => setFormData({...formData, telefone: e.target.value})}
              type="tel"
              className="w-full p-3 border border-gray-300 dark:border-gray-600 rounded-md text-sm transition-all dark:bg-gray-700 dark:text-white focus:outline-none focus:border-[#2E7D32] dark:focus:border-[#4CAF50] focus:ring-[3px] focus:ring-[#2E7D32]/10 dark:focus:ring-[#4CAF50]/10"
              placeholder="(21) 99999-9999"
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="assunto" className="block font-semibold mb-2 text-gray-700 dark:text-gray-300">Assunto *</label>
            <select
              id="assunto"
              value={formData.assunto}
              onChange={(e) => setFormData({...formData, assunto: e.target.value})}
              required
              className="w-full p-3 border border-gray-300 dark:border-gray-600 rounded-md text-sm transition-all dark:bg-gray-700 dark:text-white focus:outline-none focus:border-[#2E7D32] dark:focus:border-[#4CAF50] focus:ring-[3px] focus:ring-[#2E7D32]/10 dark:focus:ring-[#4CAF50]/10"
              disabled={loading}
            >
              <option value="">Selecione um assunto</option>
              <option value="informacao">Informação</option>
              <option value="sugestao">Sugestão</option>
              <option value="reclamacao">Reclamação</option>
              <option value="associacao">Associação</option>
              <option value="outro">Outro</option>
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="mensagem" className="block font-semibold mb-2 text-gray-700 dark:text-gray-300">Mensagem *</label>
            <textarea
              id="mensagem"
              value={formData.mensagem}
              onChange={(e) => setFormData({...formData, mensagem: e.target.value})}
              required
              rows={4}
              className="w-full p-3 border border-gray-300 dark:border-gray-600 rounded-md text-sm transition-all dark:bg-gray-700 dark:text-white focus:outline-none focus:border-[#2E7D32] dark:focus:border-[#4CAF50] focus:ring-[3px] focus:ring-[#2E7D32]/10 dark:focus:ring-[#4CAF50]/10"
              placeholder="Digite sua mensagem..."
              disabled={loading}
            ></textarea>
          </div>

          <button 
            type="submit" 
            className="w-full bg-[#2E7D32] text-white border-none rounded-md py-3 px-6 font-semibold cursor-pointer transition-all hover:bg-[#1B5E20] disabled:opacity-60 disabled:cursor-not-allowed mt-2"
            disabled={loading}
          >
            {loading ? 'Enviando...' : 'Enviar Mensagem'}
          </button>
        </form>
      </div>
    </div>
  );
}

// src/components/ui/ModalContato.vue
<!-- src/components/ui/ModalContato.vue -->
<template>
  <div 
    v-if="isOpen" 
    class="modal-overlay" 
    @click="closeOnOverlay"
  >
    <div class="modal-content" @click.stop>
      <!-- CABEÇALHO DO MODAL -->
      <div class="modal-header">
        <h2 class="modal-title">Fale Conosco</h2>
        <button @click="close" class="modal-close-btn">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- FORMULÁRIO DE CONTATO -->
      <form @submit.prevent="enviarMensagemComModal" class="modal-form">
        <div class="form-group">
          <label for="nome" class="form-label">Nome *</label>
          <input
            id="nome"
            v-model="formData.nome"
            type="text"
            required
            class="form-input"
            placeholder="Seu nome completo"
            :disabled="loading"
          />
        </div>

        <div class="form-group">
          <label for="email" class="form-label">E-mail *</label>
          <input
            id="email"
            v-model="formData.email"
            type="email"
            required
            class="form-input"
            placeholder="seu@email.com"
            :disabled="loading"
          />
        </div>

        <div class="form-group">
          <label for="telefone" class="form-label">Telefone (opcional)</label>
          <input
            id="telefone"
            v-model="formData.telefone"
            type="tel"
            class="form-input"
            placeholder="(21) 99999-9999"
            :disabled="loading"
          />
        </div>

        <div class="form-group">
          <label for="assunto" class="form-label">Assunto *</label>
          <select
            id="assunto"
            v-model="formData.assunto"
            required
            class="form-input"
            :disabled="loading"
          >
            <option value="">Selecione um assunto</option>
            <option value="informacao">Informação</option>
            <option value="sugestao">Sugestão</option>
            <option value="reclamacao">Reclamação</option>
            <option value="associacao">Associação</option>
            <option value="outro">Outro</option>
          </select>
        </div>

        <div class="form-group">
          <label for="mensagem" class="form-label">Mensagem *</label>
          <textarea
            id="mensagem"
            v-model="formData.mensagem"
            required
            rows="4"
            class="form-input"
            placeholder="Digite sua mensagem..."
            :disabled="loading"
          ></textarea>
        </div>

        <button 
          type="submit" 
          class="submit-btn"
          :disabled="loading"
        >
          <span v-if="loading">Enviando...</span>
          <span v-else>Enviar Mensagem</span>
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { useEnviarMensagem } from '@/modules/mensagens/composables/useEnviarMensagem'

// Props e Emits
const props = defineProps({
  isOpen: Boolean
})

const emit = defineEmits(['close'])

// ✅ CORREÇÃO: Criamos nosso próprio formData
const formData = reactive({
  nome: '',
  email: '',
  telefone: '',
  assunto: '',
  mensagem: ''
})

// ✅ CORREÇÃO: Usando o composable corretamente
const { loading, error, success, enviar } = useEnviarMensagem()

// Métodos
const close = () => {
  // Limpar formulário ao fechar
  Object.assign(formData, {
    nome: '',
    email: '',
    telefone: '',
    assunto: '',
    mensagem: ''
  })
  emit('close')
}

const closeOnOverlay = (event) => {
  if (event.target.classList.contains('modal-overlay')) {
    close()
  }
}

// ✅ CORREÇÃO: Enviar mensagem corretamente
const enviarMensagemComModal = async () => {
  try {
    await enviar(formData)
    
    if (success.value) {
      // Mensagem enviada com sucesso
      alert('Mensagem enviada com sucesso! Entraremos em contato em breve.')
      close()
    } else if (error.value) {
      // Mostrar erro se houver
      alert(`Erro ao enviar mensagem: ${error.value}`)
    }
  } catch (err) {
    console.error('Erro ao enviar mensagem:', err)
    alert('Erro ao enviar mensagem. Tente novamente.')
  }
}
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
  padding: 1rem;
}

.modal-content {
  background: white;
  border-radius: 12px;
  width: 100%;
  max-width: 500px;
  max-height: 90vh;
  overflow-y: auto;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
}

.dark .modal-content {
  background: #1f2937;
  color: white;
}

.modal-header {
  display: flex;
  justify-content: between;
  align-items: center;
  padding: 1.5rem;
  border-bottom: 1px solid #e5e7eb;
}

.dark .modal-header {
  border-bottom-color: #374151;
}

.modal-title {
  font-size: 1.25rem;
  font-weight: 700;
  color: #1f2937;
  margin: 0;
}

.dark .modal-title {
  color: white;
}

.modal-close-btn {
  background: none;
  border: none;
  color: #6b7280;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 4px;
  transition: all 0.2s;
}

.modal-close-btn:hover {
  color: #374151;
  background: #f3f4f6;
}

.dark .modal-close-btn:hover {
  color: white;
  background: #374151;
}

.modal-form {
  padding: 1.5rem;
}

.form-group {
  margin-bottom: 1rem;
}

.form-label {
  display: block;
  font-weight: 600;
  margin-bottom: 0.5rem;
  color: #374151;
}

.dark .form-label {
  color: #d1d5db;
}

.form-input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 0.875rem;
  transition: all 0.2s;
}

.dark .form-input {
  background: #374151;
  border-color: #4b5563;
  color: white;
}

.form-input:focus {
  outline: none;
  border-color: #2E7D32;
  box-shadow: 0 0 0 3px rgba(46, 125, 50, 0.1);
}

.dark .form-input:focus {
  border-color: #4CAF50;
  box-shadow: 0 0 0 3px rgba(76, 175, 80, 0.1);
}

.submit-btn {
  width: 100%;
  background: #2E7D32;
  color: white;
  border: none;
  border-radius: 6px;
  padding: 0.75rem 1.5rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.submit-btn:hover:not(:disabled) {
  background: #1B5E20;
}

.submit-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

/* Responsividade */
@media (max-width: 640px) {
  .modal-content {
    margin: 1rem;
    max-height: calc(100vh - 2rem);
  }
  
  .modal-header,
  .modal-form {
    padding: 1rem;
  }
}
</style>
